[tool.poetry]
name = "zanshin-cli"
version = "1.5.1"
description = "Python command line utility to the Tenchi Security Zanshin API v1"
authors = ["Tenchi Security <contact@tenchisecurity.com>"]
readme = "README.md"
packages = [{include = "zanshin_cli"}]

[tool.poetry.dependencies]
python = "^3.10"
zanshinsdk = "1.5.1"
typer = {version = "0.7.0", extras = ["all"]}
prettytable = "3.5.0"
boto3 = ">=1.26.8"
boto3-type-annotations = ">=0.3.1"


[tool.poetry.group.dev.dependencies]
moto = {version = "4.0.8", extras = ["organizations", "sts", "s3"]}
pytest = "7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
