name: Upload Python Package

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install twine
          pip install -r requirements.txt
          apt update
          apt install pandoc
          sed -i 's/__PACKAGE_VERSION__/${{ github.event.release.tag_name }}/g' zanshincli/version.py setup.py
          python setup.py install

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          rm README.md CLI.md
          make pypi
