name: Upload Python Package

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Test and Deploy to PyPI

    runs-on: ubuntu-latest
    
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          sed -i 's/__PACKAGE_VERSION__/${{ github.event.release.tag_name }}/g' zanshincli/version.py setup.py
          python setup.py install

      - name: Create fake tenchi config on Linux and Mac
        run: |
          mkdir -p $HOME/.tenchi
          touch $HOME/.tenchi/config
          echo $'[default]\napi_key = apikey\n' > $HOME/.tenchi/config

      - name: Unit tests
        run: |
          pip install -r requirements.txt
          make test

      - name: Generate updated documentation
        run: |
          apt update
          apt install pandoc
          rm README.md CLI.md README.s=rst
          make README.rst

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          make pypitest
          make pypi
