name: Upload Python Package

on:
#  release:
#    types: [created]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          sed -i 's/__PACKAGE_VERSION__/${{ github.event.release.tag_name }}/g' version.py 
          sed -i 's/__PACKAGE_VERSION__/${{ github.event.release.tag_name }}/g' setup.py
          cat version.py
          cat setup.py
#          make pypi
